/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

/**
 *
 * @author josej
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    private abrir ventana_abrir;
    private catalogo ventana_catalogo;
    private proceso ventana_proceso;
    private informe ventana_informe;
    private herramienta ventana_herramienta;
    private ayuda ventana_ayuda;

    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_abrir = new javax.swing.JMenuItem();
        menu_catalogos = new javax.swing.JMenuItem();
        menu_procesos = new javax.swing.JMenuItem();
        menu_informes = new javax.swing.JMenuItem();
        menu_herramientas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menu_ayuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        menu_abrir.setText("Abrir");
        menu_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_abrirActionPerformed(evt);
            }
        });
        jMenu1.add(menu_abrir);

        menu_catalogos.setText("Catalogos");
        menu_catalogos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_catalogosActionPerformed(evt);
            }
        });
        jMenu1.add(menu_catalogos);

        menu_procesos.setText("Procesos");
        menu_procesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_procesosActionPerformed(evt);
            }
        });
        jMenu1.add(menu_procesos);

        menu_informes.setText("Informes");
        menu_informes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_informesActionPerformed(evt);
            }
        });
        jMenu1.add(menu_informes);

        menu_herramientas.setText("Herramientas");
        menu_herramientas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_herramientasActionPerformed(evt);
            }
        });
        jMenu1.add(menu_herramientas);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        menu_ayuda.setText("Ayudas");
        menu_ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_ayudaActionPerformed(evt);
            }
        });
        jMenu2.add(menu_ayuda);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_abrirActionPerformed
        // TODO add your handling code here:
        if (ventana_abrir == null || ventana_abrir.isClosed()) {
            ventana_abrir = new abrir();
            this.add(ventana_abrir);
            ventana_abrir.setVisible(true);
        }
    }//GEN-LAST:event_menu_abrirActionPerformed

    private void menu_catalogosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_catalogosActionPerformed
        // TODO add your handling code here:
        if (ventana_catalogo == null || ventana_catalogo.isClosed()) {
            ventana_catalogo = new catalogo();
            this.add(ventana_catalogo);
            ventana_catalogo.setVisible(true);
        }
    }//GEN-LAST:event_menu_catalogosActionPerformed

    private void menu_procesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_procesosActionPerformed
        // TODO add your handling code here:
        if (ventana_proceso == null || ventana_proceso.isClosed()) {
            ventana_proceso = new proceso();
            this.add(ventana_proceso);
            ventana_proceso.setVisible(true);
        }
    }//GEN-LAST:event_menu_procesosActionPerformed

    private void menu_informesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_informesActionPerformed
        // TODO add your handling code here:
        if (ventana_informe == null || ventana_informe.isClosed()) {
            ventana_informe = new informe();
            this.add(ventana_informe);
            ventana_informe.setVisible(true);
        }
    }//GEN-LAST:event_menu_informesActionPerformed

    private void menu_herramientasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_herramientasActionPerformed
        // TODO add your handling code here:
        if (ventana_herramienta == null || ventana_herramienta.isClosed()) {
            ventana_herramienta = new herramienta();
            this.add(ventana_herramienta);
            ventana_herramienta.setVisible(true);
        }
    }//GEN-LAST:event_menu_herramientasActionPerformed

    private void menu_ayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_ayudaActionPerformed
        // TODO add your handling code here:
        if (ventana_ayuda == null || ventana_ayuda.isClosed()) {
            ventana_ayuda = new ayuda();
            this.add(ventana_ayuda);
            ventana_ayuda.setVisible(true);
        }
    }//GEN-LAST:event_menu_ayudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menu_abrir;
    private javax.swing.JMenuItem menu_ayuda;
    private javax.swing.JMenuItem menu_catalogos;
    private javax.swing.JMenuItem menu_herramientas;
    private javax.swing.JMenuItem menu_informes;
    private javax.swing.JMenuItem menu_procesos;
    // End of variables declaration//GEN-END:variables
}
